### PR TITLE
Big refactor testin

### PR DESCRIPTION
**Pull request by BOsterbuhr**
IDK

### CODE REVIEW

**Comment by BOsterbuhr** [comment]
Ok resolved the conflicts this should be good to merger but if you want to check it first I would appreciate it.

**Comment by NapsterInBlue** [comment]
I wouldn't bother merging into this branch. This is where I was trying to figure out a nuanced corner of writing unit tests-- was going to make a separate pull request when I thought it looked good.

[Another good link to read on this workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), basically 

- A: I forked a branch, `big_refactor` off of `main`, did a bunch of stuff.
- B: You forked off of my work to make `big_refactor_testin`, made a few commits, opened a PR
- C: We merged `big_refactor_testin` back into `big_refactor`, and I deleted the new branch
- D: I branched off of `big_refactor` (which included your `_testing` changes) started work on a new feature, `_mocking`
- E: It's not ready yet, but when it is, I was going to open a separate pull request to merge it back into `big_refactor`
- F: In the meantime, you can branch off of `big_refactor` to start work on `_data_save` (or finish work, if you've already done it)
- G : I'll happily code-review that and merge it into `big_refactor`, at which point it's *my problem* figuring out how to base my `_mocking` code so that it plays nicely with the code in `big_refactor` (this isn't hard to do, just tricky)
- H: We go thorough this workflow for awhile until we think this is the best, most complete version of the code, then we'd pull-request it to `main`, and delete `big_refactor` after the merge.

Dotted arrows/circles are things that haven't happened yet. Commit hashes are listed at the top, which you can cross-reference [in the Commit History](https://github.com/BOsterbuhr/FEC-Data-Wranglin/commits/big_refactor)

image

**Comment by BOsterbuhr** [comment]
Ok that makes more sense than the jankyness I was doing. Ok will reconfigure things to make it right.

**Comment by NapsterInBlue** [comment]
Cool cool. And for what it's worth, I'm hardly trying to finger-wag here. Love the initiative of tackling the next part of the project, it's just much cleaner/easier to code review/merge/iterate if we're on the same page workflow-wise.

Stepping out to grab a script and am wrist-deep in a cool work thing today, but will try and keep an eye on this thread, should you have any questions

**Pull request closed without merging**
